Repository GSG-G13/momen-mohannad-react-mini-project, pull requests merged in 2023-05, with the labels that each got.

#2 init react files
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/index.css
  src/index.js
Labels: waiting approval

#3 Project-Setup
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/AnimeItem.js
  src/components/List.js
  src/components/Navbar.js
  src/components/list.css
  src/components/nav.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: done

#4 Finish project
  src/App.js
  src/App.test.js
  src/components/AnimeItem.js
  src/components/Filters.js
  src/components/List.js
  src/components/Navbar.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: waiting
